<footer class="footer">
	<a name="contactUs"></a>
	  <div class="container">
		<h2>Contact Us</h2>
		  <div class="col-xs-12 col-md-4">
			<section>
				<img src="images/time.png" alt="Opening Hours">
				<div id="details">
					<h3>Office Hours</h3>
					<p>Monday - Friday: 9am - 5pm</p>
					<p>Saturday and Sunday: 9am - 3pm</p>
				</div>
			</section>				
		  </div>
		  <div class="col-xs-12 col-md-4">
			<section>
				<img src="images/phone.png" alt="Phone">
				<div id="details">
					<h3>Phone</h3>
					<p>During Office Hours</p>
					<p>Office Phone Line - (07)3230 2019</p>
				</div>
			</section>
		  </div>
		  <div class="col-xs-12 col-md-4">
			<section>
				<img src="images/email.png" alt="Email">
				<div id="details">
					<h3>Email</h3>
					<p>Support: support@onthespot.com.au</p>
					<p>Sales Team: sales@onthespot.com.au</p>
				</div>
			</section>
		  </div>
	  </div>
	</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="bootstrap-3.3.7/docs/assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="bootstrap-3.3.7/docs/dist/js/bootstrap.min.js"></script>
<script src="javascript/customJavascripts.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="bootstrap-3.3.7/docs/assets/js/ie10-viewport-bug-workaround.js"></script>

</body>
</html>
